# Generated by Django 3.2 on 2022-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.DateField()),
                ('workplace', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('женат', 'married'), ('в разводе', 'divorced'), ('свободен', 'single'), ('помолвлен', 'engaged')], max_length=50)),
                ('client_status', models.CharField(choices=[('активный', 'активный'), ('неактивный', 'неактивный'), ('удовлетворительный', 'удовлетворительный')], max_length=50)),
            ],
        ),
    ]
